name: 'Terraform'

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed ]

jobs:

  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: docker build -t techchallenge-eks .

      - name: Tag Docker image
        run: docker tag techchallenge-eks:latest 084477714284.dkr.ecr.us-east-1.amazonaws.com/techchallenge-eks:latest

      - name: Push Docker image to ECR
        run: docker push 084477714284.dkr.ecr.us-east-1.amazonaws.com/techchallenge-eks:latest

        # Passo adicional para configurar kubectl
      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      # Atualizar o kubeconfig para o cluster EKS
      - name: Set up EKS kubeconfig
        run: |
          aws eks --region us-east-1 update-kubeconfig --name techchallenge-cluster-eks

      # Aplicar a configuração do Kubernetes
      - name: Apply Kubernetes configuration
        run: kubectl apply -f k8s/app.yaml